services:
  postgres:
    image: postgres:16.2
    container_name: social-network-db
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./volumes/social-network-db:/var/lib/postgresql/data
    networks:
      - social-network

  pgslave:
    image: postgres:16.2
    container_name: pgslave
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - pgslave_data:/var/lib/postgresql/data
      - ./volumes/pgslave:/var/lib/postgresql/data
    networks:
      - social-network

  pgasyncslave:
    image: postgres:16.2
    container_name: pgasyncslave
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "25432:5432"
    volumes:
      - pgasyncslave_data:/var/lib/postgresql/data
      - ./volumes/pgasyncslave:/var/lib/postgresql/data
    networks:
      - social-network

  redis:
    image: redis:7.2-alpine
    container_name: social-network-redis
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - social-network

  redis-node-1: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-1
    volumes:
      - redis-node-1-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network

  redis-node-2: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-2
    volumes:
      - redis-node-2-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network

  redis-node-3: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-3
    volumes:
      - redis-node-3-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network

  redis-node-4: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-4
    volumes:
      - redis-node-4-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network
  
  redis-node-5: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-5
    volumes:
      - redis-node-5-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network
  redis-node-6: &redis-node
    image: redis:7.2-alpine
    container_name: redis-node-6
    volumes:
      - redis-node-6-data:/data
    command: >
      redis-server 
      --port 6379 
      --cluster-enabled yes 
      --cluster-config-file nodes.conf 
      --cluster-node-timeout 5000 
      --appendonly yes
    networks:
      - social-network 
  redis-cluster-creator:
    image: redis:7.2-alpine
    container_name: redis-cluster-creator
    restart: "no"
    networks:
      - social-network
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: sh -c "sleep 5 && redis-cli --cluster create redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 --cluster-replicas 1 --cluster-yes"
  rabbitmq-1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-1
    ports:
      - "5674:5672"
      - "15674:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq-1
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "7e8132a2-70eb-4f5d-a074-a96d476bdcb6"
    volumes:
      - rabbitmq_data_1:/var/lib/rabbitmq
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  rabbitmq-2:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-2
    ports:
      - "5675:5672"
      - "15675:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq-2
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "7e8132a2-70eb-4f5d-a074-a96d476bdcb6"
    volumes:
      - rabbitmq_data_2:/var/lib/rabbitmq
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  rabbitmq-3:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-3
    ports:
      - "5676:5672"
      - "15676:15672"
    environment:
      RABBITMQ_NODENAME: rabbit@rabbitmq-3
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: "7e8132a2-70eb-4f5d-a074-a96d476bdcb6"
    volumes:
      - rabbitmq_data_3:/var/lib/rabbitmq
    networks:
      - social-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: social-network-app
    restart: unless-stopped
    volumes:
      - ./people.csv:/app/people.csv
      - ./posts.txt:/app/posts.txt
    working_dir: /app
    environment:
      - CSV_PEOPLE_PATH=/app/people.csv
      - CSV_POSTS_PATH=/app/posts.txt
      - CHAT_ADDR=chat-service:5001

    ports:
      - "5001:5001"
    networks:
      - social-network
    depends_on:
      - postgres
      - redis
  ws-1:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    container_name: social-network-ws-1
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=social_network
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    networks:
      - social-network
    ports:
      - "8082:8082"
    depends_on:
      - app
    restart: unless-stopped
  chat-service:
    build:
      context: .
      dockerfile: chat-service/Dockerfile
    container_name: chat-service
    depends_on:
      redis-cluster-creator:
        condition: service_completed_successfully
    restart: unless-stopped
    ports:
      - "15005:5001"
    networks:
      - social-network
    environment:
      APP_HOST: app
      APP_PORT: 5001
    volumes:
      - ./users.csv:/app/users.csv

volumes:
  postgres_data:
    driver: local
  pgslave_data:
    driver: local
  pgasyncslave_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data_1:
   driver: local
  rabbitmq_data_2:
   driver: local
  rabbitmq_data_3:
   driver: local
  go-mod-cache:
    driver: local
  redis-cluster-creator-data:
    driver: local
  redis-node-1-data:
    driver: local
  redis-node-2-data:
    driver: local
  redis-node-3-data:
    driver: local
  redis-node-4-data:
    driver: local
  redis-node-5-data:
    driver: local
  redis-node-6-data:
    driver: local

networks:
  social-network:
    driver: bridge