syntax = "proto3";

package chat;

option go_package = "chat-service/pkg/pb/chat"; 

service ChatService {
  rpc SendMessage (SendMessageRequest) returns (MessageResponse);
  rpc GetMessagesByUser (GetDialogRequest) returns (DialogResponse);
}

message SendMessageRequest {
  string recipient_id = 1;
  string content = 2;
}

message MessageResponse {
  string sender_id = 1;
  string recipient_id = 2;
  string content = 3;
}

message GetDialogRequest {
  string friend_id = 1;
  int32 limit = 2;
  int32 offset = 3;
}

message Message {
  string sender_id = 1;
  string recipient_id = 2;
  string content = 3;
}

message DialogResponse {
  repeated Message messages = 1;
}